### ISSUE TITLE
Create Account - Char limits and password issues

### ISSUE THREAD

**Issue by gen1e** [Women-in-Computing-at-RIT/AlumniApp#3]
Need to address the character limits - currently defaulted to 30 chars.

Also need to address password strength - currently defaulted to just check for a special char, a capital letter, and a number.
We may want to make sure the password doesn't have dictionary words in it - would need to figure out how to do that.
@dquach217 is working on ecrypting the password in the Create account class.

Also need to address how we want to verify that the person is an RIT student - right now we are using an RIT email as most current students and most recent alumni would still have them. Need to address how to potentially vet alumni.

**Comment by gen1e** [comment]
Soemthing to consider using to check passwords: https://github.com/dropbox/zxcvbn

**Comment by glossawy** [comment]
Alternatively you could look into Passwordless authentication or passing this off to a separate service (securely) to avoid the trap that can be credential security: 

- https://auth0.com/
- https://www.authy.com/

Even better, talk to people in SITO or other faculty who may have information to maybe integrate with RIT's Shibboleth Single-Sign-On (SSO) service. Another good alternative would be integrating with other services like Google+/Facebook/LinkedIn with OAuth2/OpenId (which Auth0 can help with).

Otherwise zxcvbn is fantastic. Just be sure to use libraries where appropriate if you are going to store passwords. Though I figure you are handling that. 😄
